import { Footer } from "@/components/globals/footer";
import { Loading } from "@/components/globals/loading";
import { SmootherProvider } from "@/hooks/use-smoother";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Header } from "../components/globals/header";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prime Poker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${montserrat.variable}`}>
      <body className="antialiased">
        <SmootherProvider>
          <Header />
          <div id="smooth-wrapper">
            <div id="smooth-content">
              {children}
              <Footer />
            </div>
          </div>
        </SmootherProvider>
        <Loading />
      </body>
    </html>
  );
}
